# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# Setup dircolors only if available
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
fi

# Set ls alias conditionally for macOS and Linux
if [[ "$OSTYPE" == "darwin"* ]]; then
    alias ls='ls -G'  # macOS uses -G for colors
    alias aw='aerospace list-windows --workspace'
    alias bash='/opt/homebrew/bin/bash'
else
    alias ls='ls --color=auto'  # Linux uses --color=auto
fi

# Always set color support for grep, fgrep, and egrep
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias ll='ls -ltr'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
if [[ "$OSTYPE" == "darwin"* ]]; then
    alias alert='osascript -e "display notification \"$(history | tail -n1 | sed -e 's/^\s*[0-9]\+\s*//')\" with title \"Alert\""'
else
    alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history | tail -n1 | sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
fi

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
    if [[ "$OSTYPE" == "darwin"* ]]; then
        # macOS completion
        if [ -f /opt/homebrew/etc/bash_completion ]; then
            . /opt/homebrew/etc/bash_completion
        fi
        if [ -f ~/projects/misc/.git-completion.bash ]; then
            . ~/projects/misc/.git-completion.bash
        fi
    else
        # Linux completion
        if [ -f /usr/share/bash-completion/bash_completion ]; then
            . /usr/share/bash-completion/bash_completion
        elif [ -f /etc/bash_completion ]; then
            . /etc/bash_completion
        fi
    fi
fi

# Handle PATH modifications to avoid redundancy
add_to_path() {
    case ":$PATH:" in
        *":$1:"*) ;;  # Already in PATH
        *) export PATH="$1:$PATH" ;;
    esac
}

# Add platform-specific paths
if [[ "$OSTYPE" == "darwin"* ]]; then
    add_to_path "/opt/homebrew/bin"
    add_to_path "$HOME/Library/Python/3.11/bin"
else
    add_to_path "/usr/local/bin"
fi

export PATH="$PATH:/opt/nvim-linux64/bin"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
. "$HOME/.cargo/env"

source ~/projects/personal/codeprompts/completions/codeprompt-completions.bash
