# Set up Homebrew's PATH, MANPATH, and HOMEBREW_PREFIX
if [[ "$OSTYPE" == "darwin"* ]]; then
    if [ -x /opt/homebrew/bin/brew ]; then
        eval "$(/opt/homebrew/bin/brew shellenv)"
    elif [ -x /usr/local/bin/brew ]; then
        eval "$(/usr/local/bin/brew shellenv)"
    fi
fi

if [ -f ~/.bashrc ]; then
    source ~/.bashrc
fi
